-- Descricoes importadas de Book 2(Planilha1).csv.
-- Mantem imagens ja carregadas no dump ou em outros seeds.
INSERT INTO empresa_infos (empresa_id, descricao, caminho_imagem) VALUES
(751,'A Mahle Rede de Postos é uma empresa brasileira do setor de combustíveis que atua há mais de 35 anos no mercado, oferecendo serviços de abastecimento, conveniência e atendimento para motoristas e transportadoras. A rede possui dezenas de unidades distribuídas em diferentes estados do Brasil, com foco em combustíveis de qualidade, estrutura moderna e atendimento humanizado. Além dos postos de combustível, o grupo também investe em programas de fidelidade, tecnologia e serviços voltados para quem viaja pelas rodovias brasileiras.',NULL),
(754,'A Genótika Sementes é uma empresa brasileira do agronegócio especializada no desenvolvimento, produção e comercialização de sementes híbridas de milho e variedades de soja. Fundada no Centro-Oeste do Brasil, a empresa atua com foco em tecnologia, pesquisa genética e alto desempenho no campo, oferecendo soluções voltadas para aumento de produtividade e rentabilidade dos produtores rurais. A Genótika destaca-se pelo compromisso com inovação, qualidade das sementes e suporte ao agricultor em diferentes regiões do país.',NULL),
(759,'A Grupo Comber é uma empresa brasileira fundada em 1986 que atua nos setores de logística, manejo florestal, biomassa e energia renovável. Originada como uma empresa familiar em Santa Catarina, a companhia evoluiu do setor madeireiro para operações de transporte e, posteriormente, para soluções sustentáveis voltadas ao agronegócio e à produção de biomassa. Atualmente, o grupo possui unidades em diversos estados do Brasil, com forte presença no Centro-Oeste, destacando-se pelo processamento de biomassa, reflorestamento, transporte florestal e inovação industrial voltada à sustentabilidade.',NULL),
(761,'A Posto de Lavagem Rio Sul é uma empresa goiana fundada em 2007, especializada em serviços automotivos como lavagem, lubrificação, polimento e manutenção básica de veículos. Localizada no Distrito Agroindustrial de Rio Verde (GO), a empresa atua com foco em agilidade, qualidade no atendimento e conservação automotiva, atendendo clientes da região com serviços voltados para limpeza e cuidados veiculares.',NULL),
(765,'A Mecânica Videira é uma empresa localizada em Rio Verde (GO), especializada em manutenção e reparo de caminhões e veículos pesados. Atuando no Distrito Agroindustrial de Rio Verde II, a oficina se destaca pelo atendimento voltado ao setor de transporte e logística, oferecendo serviços mecânicos com foco em qualidade, agilidade e confiança. Fundada em 2006, a empresa atende principalmente frotistas, transportadoras e profissionais do agronegócio da região.',NULL),
(768,'A Copecar
 é uma empresa brasileira especializada na fabricação, venda e distribuição de peças e equipamentos para máquinas agrícolas, com forte atuação no setor hidráulico e sucroenergético. Com mais de 40 anos de mercado, a empresa oferece soluções para colhedoras, carregadeiras de cana e sistemas hidráulicos, trabalhando com marcas reconhecidas como Eaton, Parker, Danfoss e Aeroquip.

A companhia também atua com manutenção preventiva e corretiva de componentes hidráulicos, além de suporte técnico para o agronegócio e indústrias. Possui unidades em Ribeirão Preto (SP), Presidente Prudente (SP) e Rio Verde (GO), destacando-se pela qualidade, confiabilidade e inovação no atendimento aos produtores rurais e empresas do setor agrícola.',NULL),
(771,'A Canatec Serviços Ltda é uma empresa goiana fundada em 2016, especializada em serviços agrícolas, preparação de solo, cultivo e colheita. Localizada em Rio Verde (GO), a empresa atua fortemente no agronegócio, oferecendo soluções para operações agrícolas mecanizadas, além de serviços de apoio à agricultura, manutenção de máquinas agrícolas, terraplanagem e transporte de cargas.

Com atuação voltada principalmente ao setor sucroenergético e agrícola, a Canatec se destaca pelo suporte operacional no campo, utilização de maquinário especializado e atendimento a produtores rurais e empresas do agronegócio da região Centro-Oeste.',NULL),
(774,'A MMZ Mecânica Industrial é uma empresa especializada no setor metal mecânico, atuando com montagem industrial, manutenção, reforma de equipamentos e usinagem para indústrias alimentícias e frigoríficas no Brasil e no exterior. Localizada em Rio Verde (GO), a empresa oferece soluções para processamento de alimentos bovinos, suínos e aves, realizando manutenção em máquinas industriais, sistemas hidráulicos e pneumáticos, motoredutores, túneis de cozimento e diversos equipamentos utilizados na indústria frigorífica.

A empresa conta com equipes qualificadas de soldadores, caldeireiros, montadores e mecânicos industriais, destacando-se pela prestação de serviços técnicos especializados, fabricação de peças e suporte industrial para o agronegócio e setor alimentício.',NULL),
(776,'A KADE Engenharia e Construção Ltda é uma empresa brasileira do setor de construção civil e engenharia, atuando na execução de obras, terraplanagem e projetos de infraestrutura. Fundada em 1985, a empresa também trabalha com atividades ligadas à extração e fornecimento de materiais para construção. Com atuação em diferentes regiões do país, incluindo Goiás, a KADE atende demandas de obras industriais, privadas e de infraestrutura, oferecendo serviços técnicos e operacionais no setor.',NULL),
(777,'A Trans Magnabosco é uma empresa brasileira de transporte rodoviário de cargas, fundada em 1981 em Santa Catarina. Atua em todo o país, incluindo o Centro-Oeste, realizando o transporte de cargas secas, refrigeradas e do agronegócio.

A empresa se destaca pela frota moderna, foco em segurança e pontualidade, além de atender grandes clientes do setor logístico e industrial.',NULL),
(779,'A PJR Armazenagem é uma empresa brasileira especializada em soluções de armazenagem e logística para o agronegócio. Atuando principalmente no setor agrícola, a empresa oferece serviços voltados ao armazenamento de grãos, movimentação de cargas e suporte logístico, contribuindo para a conservação e escoamento da produção rural.

A PJR se destaca pelo foco em eficiência operacional, estrutura de armazenagem e atendimento às demandas de produtores e empresas do agronegócio da região Centro-Oeste.',NULL),
(782,'A WR Montagens é uma empresa brasileira especializada em montagem e manutenção industrial, atuando com serviços voltados à instalação de equipamentos, estruturas metálicas e manutenção de máquinas industriais. A empresa atende principalmente setores industriais e do agronegócio, oferecendo soluções técnicas com foco em qualidade, segurança e eficiência operacional.

Além das atividades de montagem industrial, a WR também realiza serviços de manutenção corretiva e preventiva, buscando atender demandas de indústrias e empresas que necessitam de suporte técnico especializado.',NULL),
(785,'A Refriar Ar Condicionado é uma empresa de Rio Verde (GO) especializada em ar-condicionado automotivo, refrigeração e climatização para veículos, caminhões e máquinas agrícolas. Fundada originalmente em 1984 como FrigoMac, a empresa passou a atuar como Refriar em 2000, tornando-se referência no Centro-Oeste no segmento de refrigeração automotiva.

A empresa oferece instalação, manutenção e venda de peças para sistemas de ar-condicionado, contando com mais de 3 mil itens à pronta entrega e assistência técnica especializada. A Refriar também é autorizada da Denso do Brasil e parceira de grandes marcas do setor, destacando-se pela qualidade dos serviços, estrutura própria e equipe técnica qualificada.',NULL),
(787,'A Videplast é uma das principais indústrias brasileiras de embalagens plásticas flexíveis, fundada em 1986 em Videira (SC). A empresa atua na produção de embalagens para diversos segmentos, como alimentos, agronegócio, indústria farmacêutica, petfood e produtos industriais.

Com unidades em vários estados do Brasil, incluindo Goiás, Mato Grosso, Paraná e Rio de Janeiro, a Videplast se destaca pelo investimento em tecnologia, inovação e sustentabilidade, oferecendo soluções de alta qualidade para o mercado nacional e internacional.',NULL),
(790,'A Klabin é uma das maiores empresas brasileiras do setor de papel e celulose, fundada em 1899. A companhia é líder na produção e exportação de papéis para embalagens e soluções sustentáveis em papel no Brasil, atuando também na fabricação de celulose, papelão ondulado, sacos industriais e embalagens recicláveis.

Com unidades industriais em diversos estados do país, a empresa se destaca pelo forte investimento em inovação, manejo florestal sustentável e preservação ambiental, sendo reconhecida internacionalmente por suas práticas de sustentabilidade e eficiência operacional.',NULL)
ON DUPLICATE KEY UPDATE
    descricao = VALUES(descricao),
    caminho_imagem = COALESCE(empresa_infos.caminho_imagem, VALUES(caminho_imagem));
