CREATE TABLE IF NOT EXISTS municipio (
    municipio_id INT NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    PRIMARY KEY (municipio_id)
);

INSERT INTO municipio (municipio_id, municipio) VALUES
    (1, 'ABADIANIA'),
    (2, 'ANAPOLIS'),
    (3, 'ANICUNS'),
    (4, 'APARECIDA DE GOIANIA'),
    (5, 'BELA VISTA DE GOIAS'),
    (6, 'CALDAS NOVAS'),
    (7, 'CATALAO'),
    (8, 'CERES'),
    (9, 'GOIANESIA'),
    (10, 'GOIANIRA'),
    (11, 'GOIAS'),
    (12, 'GOIATUBA'),
    (13, 'INHUMAS'),
    (14, 'IPORA'),
    (15, 'ITAPURANGA'),
    (16, 'ITUMBIARA'),
    (17, 'JUSSARA'),
    (18, 'LUZIANIA'),
    (19, 'MAIRIPOTABA (CONDOMINIO)'),
    (20, 'MARZAGAO (CONDOMINIO)'),
    (21, 'MINEIROS'),
    (22, 'MORRINHOS'),
    (23, 'ORIZONA'),
    (24, 'PADRE BERNARDO'),
    (25, 'PARAUNA'),
    (26, 'PETROLINA'),
    (27, 'PETROLINA DE GOIAS'),
    (28, 'PIRACANJUBA'),
    (29, 'PIRENOPOLIS'),
    (30, 'PONTALINA'),
    (31, 'PORANGATU'),
    (32, 'POSSE'),
    (33, 'RIALMA'),
    (34, 'RIO VERDE'),
    (35, 'RUBIATABA'),
    (36, 'SAO LUIS DE MONTES BELOS'),
    (37, 'SAO LUIZ DO NORTE'),
    (38, 'SAO LUIZ DOS MONTES BELOS'),
    (39, 'SAO MIGUEL DO ARAGUAIA'),
    (40, 'SENADOR CANEDO'),
    (41, 'URUACU')
ON DUPLICATE KEY UPDATE municipio = VALUES(municipio);
